-- Database aanmaken en gebruiken
DROP DATABASE IF EXISTS VlamComDB;
CREATE DATABASE VlamComDB;
USE VlamComDB;

-- Tabel Afdelingen
DROP TABLE IF EXISTS Afdelingen;
CREATE TABLE Afdelingen (
    AfdelingID INT AUTO_INCREMENT PRIMARY KEY,
    AfdelingNaam VARCHAR(50) NOT NULL
);

-- Tabel Medewerkers
DROP TABLE IF EXISTS Medewerkers;
CREATE TABLE Medewerkers (
    MedewerkerID INT AUTO_INCREMENT PRIMARY KEY,
    Voornaam VARCHAR(50),
    Achternaam VARCHAR(50),
    Functie VARCHAR(50),
    AfdelingID INT,
    Locatie VARCHAR(50),
    Salaris DECIMAL(10, 2),
    FOREIGN KEY (AfdelingID) REFERENCES Afdelingen(AfdelingID)
);

-- Afdelingen invoegen
INSERT INTO Afdelingen (AfdelingNaam) VALUES 
('Ontwikkeling'),
('Ondersteuning'),
('Verkoop'),
('Marketing'),
('HR');

-- Medewerkers invoegen met salaris
INSERT INTO Medewerkers (Voornaam, Achternaam, Functie, AfdelingID, Locatie, Salaris)
VALUES 
('Jan', 'Peeters', 'Software Engineer', 1, 'Balen', 3500.00),
('Sofie', 'Janssens', 'Project Manager', 1, 'Oud-Turnhout', 4500.00),
('Kurt', 'Vanschoonbeek', 'Support Specialist', 2, 'Baarle Hertog', 3000.00),
('Bas', 'Sillen', 'Sales Representative', 3, 'Mol', 3200.00),
('Maarten', 'Verhoeven', 'Marketing Specialist', 4, 'Turnhout', 3600.00),
('Amina', 'El Amrani', 'Software Tester', 2, 'Turnhout', 2900.00),
('Emre', 'Yılmaz', 'Front-End Developer', 1, 'Oud-Turnhout', 3700.00),
('Leonie', 'Schmidt', 'Project Coordinator', 5, 'Geel', 3800.00),
('Hans', 'Schoen', 'Marketing Specialist', 4, 'Mol', 3400.00),
('Kenny', 'Boeijen', 'Sales Manager', 3, 'Turnhout', 4100.00),
('Ali', 'Kara', 'System Administrator', 2, 'Oud-Turnhout', 4000.00),
('Nina', 'Müller', 'Data Scientist', 1, 'Weelde', 4500.00),
('Wil', 'Bierman', 'Business Analyst', 3, 'Arendonk', 4300.00),
('Zeynep', 'Demir', 'Technical Writer', 5, 'Beerse', 3200.00),
('Khalid', 'Haddad', 'Network Engineer', 1, 'Turnhout', 3600.00),
('Tom', 'Brouwers', 'UX Designer', 1, 'Geel', 3800.00),
('Ellen', 'Vermuelen', 'Sales Assistant', 3, 'Mol', 2900.00),
('Milan', 'Jacobs', 'Content Marketer', 4, 'Turnhout', 3300.00),
('Hannah', 'Klein', 'Business Development', 2, 'Antwerpen', 3100.00),
('Victor', 'Beyer', 'Product Owner', 1, 'Geel', 4700.00),
('Ron', 'De Bil', 'Software Architect', 1, 'Mol', 5000.00),
('Yasin', 'Aydin', 'Helpdesk Technician', 2, 'Turnhout', 2800.00),
('Lara', 'Schmitt', 'HR Consultant', 5, 'Oud-Turnhout', 4200.00),
('Sam', 'Bal', 'Graphic Designer', 4, 'Geel', 3400.00),
('Justin', 'Case', 'SEO Specialist', 3, 'Mol', 3300.00),
('Mika', 'Fischer', 'IT Manager', 2, 'Dessel', 4900.00),
('Wouter', 'Dewaele', 'Data Analyst', 1, 'Herentals', 3700.00),
('Liv', 'Frie', 'Social Media Manager', 4, 'Geel', 3400.00),
('Peter', 'Kramer', 'Backend Developer', 1, 'Mol', 4200.00),
('Bas', 'Ketbal', 'Sales Executive', 3, 'Turnhout', 3600.00),
('Ruben', 'Brouwer', 'Frontend Developer', 1, 'Beerse', 3800.00),
('Jasper', 'Nijhuis', 'Database Administrator', 2, 'Geel', 3900.00),
('Fee', 'Mos', 'Marketing Intern', 4, 'Mol', 2000.00),
('Sophie', 'Wagner', 'Quality Assurance', 2, 'Turnhout', 3100.00),
('Inge', 'Licht', 'Customer Success Manager', 3, 'Oud-Turnhout', 3600.00),
('Irene', 'Meyer', 'Business Analyst', 1, 'Geel', 4000.00),
('Daan', 'Van Dijk', 'Operations Manager', 2, 'Retie', 4500.00),
('Anouk', 'Van der Meer', 'Sales Consultant', 3, 'Turnhout', 3000.00),
('Zara', 'Karaman', 'Software Developer', 1, 'Herentals', 3900.00),
('Kaat', 'Bouter', 'Project Manager', 1, 'Geel', 4400.00),
('Matteo', 'Rossi', 'Web Developer', 1, 'Mol', 3700.00),
('Arzu', 'Öztürk', 'IT Support', 2, 'Turnhout', 2900.00),
('Timo', 'Jansen', 'Software Engineer', 1, 'Retie', 3600.00),
('Amira', 'Sidi', 'HR Assistant', 5, 'Geel', 2800.00),
('Benny', 'Dom', 'Digital Marketing Specialist', 4, 'Mol', 3300.00),
('Dirk', 'Teur', 'CEO', 5, 'Arendonk', 6400.00),
('Gizem', 'Demirtaş', 'Marketing Assistant', 4, 'Kasterlee', 3000.00),
('Elias', 'Schäfer', 'Business Analyst', 3, 'Geel', 3200.00),
('Sienna', 'López', 'Social Media Specialist', 4, 'Vosselaar', 3400.00),
('Samir', 'Boukhlifa', 'Customer Support', 2, 'Turnhout', 2900.00),
('Julia', 'Klein', 'Data Entry Clerk', 2, 'Retie', 2700.00),
('Piet', 'Saman', 'Sales Manager', 3, 'Geel', 4200.00),
('Bennie', 'Thuis', 'Operations Assistant', 5, 'Mol', 2600.00),
('Niels', 'Visser', 'Technical Consultant', 1, 'Oud-Turnhout', 4100.00),
('Ria', 'Lopez', 'Head of Development', 1, 'Herentals', 5000.00),
('Cor', 'Netto', 'IT Support Technician', 2, 'Merksplas', 2800.00),
('Chris', 'Mus', 'Project Coordinator', 1, 'Mol', 3600.00),
('Bram', 'Dumont', 'Frontend Engineer', 1, 'Turnhout', 3700.00),
('Beau', 'ter Ham', 'Software Tester', 2, 'Kasterlee', 3200.00),
('Jelena', 'Kostić', 'UX Researcher', 4, 'Geel', 3400.00),
('Theo', 'González', 'Marketing Analyst', 4, 'Mol', 3600.00),
('Co', 'De Kraker', 'Database Analyst', 2, 'Turnhout', 3900.00),
('Elif', 'Akman', 'Customer Relations Manager', 3, 'Eindhoven', 4100.00),
('Mira', 'Lehmann', 'Software Engineer', 1, 'Lommel', 4500.00),
('Joska', 'Bouter', 'Web Designer', 1, 'Mol', 3700.00),
('Filip', 'Sturm', 'SEO Expert', 4, 'Turnhout', 4000.00),
('Peter', 'Celie', 'Graphic Designer', 4, 'Herentals', 3400.00),
('Okan', 'Kurt', 'Network Administrator', 2, 'Geel', 3800.00),
('Selin', 'Güler', 'Content Creator', 4, 'Mol', 3200.00),
('Max', 'Schmitt', 'IT Consultant', 1, 'Turnhout', 4300.00),
('Conny', 'Plassen', 'Software Developer', 1, 'Kasterlee', 3600.00),
('Magda', 'Wellens', 'Business Developer', 3, 'Retie', 3700.00),
('Khalid', 'Nour', 'Technical Support', 2, 'Oud-Turnhout', 2900.00),
('Alice', 'Schwarz', 'Operations Manager', 5, 'Turnhout', 4500.00),
('Hakan', 'Gürbüz', 'Software Engineer', 1, 'Merksplas', 3900.00),
('Freya', 'Wolf', 'Marketing Executive', 4, 'Ravels', 3300.00),
('Kasim', 'Altun', 'Data Scientist', 1, 'Mol', 4400.00),
('Matias', 'Cruz', 'SEO Specialist', 4, 'Turnhout', 3500.00),
('Asma', 'Abouda', 'Sales Executive', 3, 'Herentals', 3700.00),
('Jona', 'Schmidt', 'Helpdesk Technician', 2, 'Kasterlee', 3100.00),
('Carmen', 'Rodriguez', 'Project Manager', 1, 'Retie', 4700.00),
('Marta', 'Sanchez', 'Customer Service', 2, 'Turnhout', 2900.00),
('Can', 'Kaya', 'Social Media Manager', 4, 'Herentals', 3400.00),
('Aylin', 'Duman', 'Sales Assistant', 3, 'Geel', 3200.00),
('Magda', 'Soms', 'UX Designer', 4, 'Mol', 3400.00),
('Zelda', 'Kramer', 'Business Analyst', 1, 'Ravels', 4200.00),
('Emine', 'Öztürk', 'Technical Writer', 2, 'Oud-Turnhout', 3000.00),
('Sjef', 'Kock', 'Product Manager', 1, 'Kasterlee', 4600.00),
('Dies', 'Goorman', 'Data Analyst', 1, 'Mol', 3500.00),
('Mehmet', 'Ozturk', 'Backend Developer', 1, 'Turnhout', 3700.00),
('Mireille', 'Duval', 'Marketing Director', 4, 'Herentals', 5400.00),
('Han', 'Burger', 'Frontend Developer', 1, 'Kasterlee', 3800.00),
('Dierk', 'Triese', 'HR Manager', 5, 'Kasterlee', 4200.00),
('Bnnny', 'Goedman', 'Database Administrator', 2, 'Turnhout', 3900.00),
('Leon', 'Berg', 'IT Specialist', 1, 'Herentals', 4300.00),
('Alberto', 'Gomez', 'Content Writer', 4, 'Kasterlee', 3100.00),
('Murat', 'Çelik', 'Support Technician', 2, 'Poppel', 2700.00),
('Tijs', 'Vermeulen', 'Software Engineer', 1, 'Antwerpen', 3200.00),
('Aagje', 'Krause', 'Projectmanager', 2, 'Brugge', 2900.00),
('Wil', 'Sneller', 'System Administrator', 3, 'Kortrijk', 3100.00),
('Maud', 'Dumont', 'UX Designer', 4, 'Oostende', 2800.00),
('Ann', 'Gel', 'Data Analist', 1, 'Dendermonde', 3500.00),
('Bram', 'Willems', 'Business Analyst', 2, 'Hasselt', 3000.00),
('Lies', 'Verhoeven', 'Netwerkbeheerder', 3, 'Leuven', 3300.00),
('Yara', 'Claus', 'Marketing Specialist', 4, 'Tienen', 2700.00),
('Ton', 'Van Hout', 'Full Stack Developer', 1, 'Sint-Niklaas', 3400.00),
('Nina', 'Beyers', 'HR Medewerker', 2, 'Mechelen', 2800.00),
('Otto', 'Van Den Broeck', 'Support Engineer', 3, 'Turnhout', 2900.00),
('Aline', 'Janssens', 'Content Manager', 4, 'Geel', 3100.00),
('Hans', 'Som', 'SEO Specialist', 1, 'Hasselt', 3200.00),
('Pie', 'Kant', 'Sales Executive', 2, 'Roeselare', 3000.00),
('Bennie', 'Koekoek', 'DevOps Engineer', 3, 'Kortrijk', 3300.00),
('Tessa', 'Schmidt', 'Test Engineer', 4, 'Antwerpen', 2800.00),
('Niels', 'Peters', 'Software Tester', 1, 'Brugge', 3100.00),
('Daan', 'Brouwers', 'System Architect', 2, 'Leuven', 3500.00),
('Hannah', 'De Vries', 'Customer Success Manager', 3, 'Mechelen', 3200.00),
('Max', 'Van der Meer', 'Technical Writer', 4, 'Sint-Niklaas', 2900.00),
('Jasper', 'Meyers', 'Data Scientist', 1, 'Oostende', 3400.00),
('Silke', 'Willems', 'Product Owner', 2, 'Dendermonde', 3300.00),
('Lars', 'Vandenberghe', 'Software Developer', 3, 'Hasselt', 3000.00),
('Bo', 'Relnoot', 'Front-end Developer', 4, 'Roeselare', 3100.00),
('Stijn', 'Clijsters', 'Back-end Developer', 1, 'Antwerpen', 2800.00),
('Anna', 'Nas', 'Graphic Designer', 2, 'Brugge', 2900.00),
('Ruben', 'Van der Linden', 'IT Consultant', 3, 'Turnhout', 3200.00),
('Joke', 'Van Acker', 'Business Consultant', 4, 'Geel', 3000.00),
('Lies', 'Bets', 'Network Engineer', 1, 'Kortrijk', 3400.00),
('Cato', 'Tack', 'Helpdesk Medewerker', 2, 'Leuven', 2800.00),
('Fien', 'Peeters', 'Software Architect', 3, 'Hasselt', 3100.00),
('Hugo', 'Clemens', 'Test Coördinator', 4, 'Oostende', 2900.00),
('Yelle', 'Klein', 'UI Designer', 1, 'Sint-Niklaas', 3300.00),
('Rosa', 'Lemaire', 'Business Development Manager', 2, 'Dendermonde', 3200.00),
('Liam', 'Dumont', 'Cloud Engineer', 3, 'Brugge', 3500.00),
('Liesbeth', 'Verhaegen', 'Database Administrator', 4, 'Roeselare', 3000.00),
('Luca', 'Heijmans', 'Security Specialist', 1, 'Antwerpen', 3400.00),
('Nora', 'Vandenbossche', 'Social Media Manager', 2, 'Mechelen', 2900.00),
('Lennert', 'Maes', 'E-commerce Specialist', 3, 'Kortrijk', 3100.00),
('Maya', 'Aerts', 'Systeemanalist', 4, 'Leuven', 2800.00),
('Ilias', 'Biermans', 'Mobile Developer', 1, 'Turnhout', 3300.00),
('Naomi', 'Geerts', 'Content Creator', 2, 'Hasselt', 3200.00),
('Kyan', 'Verlinden', 'SEO Analyst', 3, 'Oostende', 2900.00),
('Liv', 'Ter Oplos', 'Data Analyst', 4, 'Dendermonde', 3100.00),
('Quinten', 'Willekens', 'Helpdesk Specialist', 1, 'Roeselare', 3000.00),
('Amelie', 'Van Gorp', 'Sales Manager', 2, 'Antwerpen', 3500.00),
('Thijs', 'Stroobants', 'Software Engineer', 3, 'Brugge', 3300.00),
('Ka', 'Ching', 'IT Manager', 4, 'Sint-Niklaas', 5800.00),
('Tomas', 'Schelfhout', 'Logistiek Medewerker', 1, 'Leuven', 2800.00),
('Fran', 'Siens', 'HR Consultant', 2, 'Mechelen', 3000.00),
('Lieselotte', 'Van Thielen', 'Quality Assurance Engineer', 3, 'Turnhout', 3100.00),
('Stef', 'Bousser', 'Business Intelligence Analyst', 4, 'Kortrijk', 2900.00),
('Fleur', 'Bloemen', 'Support Specialist', 1, 'Dendermonde', 2800.00),
('Luca', 'Dumont', 'Marketing Manager', 2, 'Hasselt', 3300.00),
('Saar', 'De Nijs', 'Software Tester', 3, 'Antwerpen', 3100.00),
('Fien', 'Dille', 'Project Coördinator', 4, 'Brugge', 3000.00),
('Sebastiaan', 'Hansen', 'UX Researcher', 1, 'Sint-Niklaas', 3200.00),
('Evelien', 'Eloi', 'Data Engineer', 2, 'Kortrijk', 3400.00);


commit;
